export enum ShowStatusEnum {
  None = 0,
  Running = 1,
  Ended = 2,
  To_Be_Determined = 3,
  In_Development = 4,
}
export enum None {
  None = 0,
}
export enum ShowTypeEnum {
  None = 0,
  Scripted = 1,
  Animation = 2,
  Reality = 3,
  Talk_Show = 4,
  Documentary = 5,
  Game_Show = 6,
  News = 7,
  Sports = 8,
  Variety = 9,
  Award_Show = 10,
  Panel_Show = 11,
}
export enum ShowGenreEnum {
  None = 0,
  Action = 3,
  Adult = 19,
  Adventure = 4,
  Anime = 5,
  Children = 6,
  Comedy = 2,
  Crime = 8,
  DIY = 24,
  Drama = 1,
  Espionage = 25,
  Family = 9,
  Fantasy = 10,
  Food = 7,
  History = 23,
  Horror = 11,
  Legal = 27,
  Medical = 22,
  Music = 12,
  Mystery = 18,
  Nature = 20,
  Romance = 13,
  Science_Fiction = 14,
  Sports = 26,
  Supernatural = 28,
  Thriller = 15,
  Travel = 21,
  War = 16,
  Western = 17,
}

export enum SortEnum {
  Most_popular = 1,
  Least_popular = 2,
  Highest_rating = 7,
  Lowest_rating = 8,
  A_to_Z = 3,
  Z_to_A = 4,
  Most_recently_added = 5,
  Least_recently_added = 6,
  Most_followed = 9,
}
